---

- name: Download war file from Jenkins
  get_url:
    url: http://{{ jenkins_instance }}:{{ jenkins_port }}/jenkins/job/{{ job_name }}/lastBuild/execution/node/3/ws/target/hello-1.0.war
    dest: "{{ tomcat_home }}/webapps/"
    username: "{{ jenkins_username }}"
    password: "{{ jenkins_token }}"
    force_basic_auth: yes
    
- name: Start tomcat
  systemd:
    state: started
    name: tomcat.service
